name: 'Printing Vars'
on:
  workflow_dispatch:

jobs:
  PrintingVars:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Print Repo Variable
        run: |
          echo ${{ vars.username }}

      - name: Print Repo Variable
        run: |
          echo ${{ secrets.passkey }}

      - name: Print Repo Variable
        run: |
          echo ${{ vars.Id }}
      
      - name: Print Repo Variable
        run: |
          echo ${{ secrets.apikey }}
        
